# Generated by Django 4.1 on 2022-08-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIManager', '0003_filleddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('formData', models.CharField(default='m', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='NodeParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('formData', models.CharField(default='m', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='FilledData',
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
        migrations.DeleteModel(
            name='FormFiller',
        ),
        migrations.DeleteModel(
            name='PublicFormData',
        ),
    ]
