# Generated by Django 4.1 on 2022-09-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIManager', '0004_nodedata_nodeparams_delete_filleddata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodedata',
            old_name='formData',
            new_name='nodeData',
        ),
        migrations.RenameField(
            model_name='nodeparams',
            old_name='formData',
            new_name='nodeData',
        ),
    ]
